import 'package:health_ministry_research_library/imports.dart';

List<ResearchDocumentModel> researchDocumentModelFromJson(String str) =>
    List<ResearchDocumentModel>.from(
        json.decode(str).map((x) => ResearchDocumentModel.fromJson(x)));

String researchDocumentModelToJson(List<ResearchDocumentModel> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class ResearchDocumentModel {
  ResearchDocumentModel({
    this.ID,
    this.data_source,
    this.file_name,

    ///--------------------- A. The source study or studies ---------------------///
    ///------------------ MANDATORY
    this.sourceStudyTitle,

    ///------------------ RECOMMENDED
    this.studyIdentifierRecords,
    this.studyTopics,

    ///------------------ OPTIONAL

    ///--------------------- B. Data object characteristics and object identifiers  ---------------------///
    ///------------------ MANDATORY
    this.DOI,
    this.objectTitle,

    ///------------------ RECOMMENDED
    this.version,

    ///------------------ OPTIONAL
    this.objectOtherIdentifiers,
    this.objectAdditionalTitles,

    ///--------------------- C. Data object characteristics and object identifiers ---------------------///
    ///------------------ MANDATORY
    this.creators,

    ///------------------ RECOMMENDED
    ///------------------ OPTIONAL
    this.contributors,

    ///--------------------- D. Data object characteristics and object identifiers ---------------------///
    ///------------------ MANDATORY
    this.creationYear,

    ///------------------ RECOMMENDED
    ///------------------ OPTIONAL
    this.dates,

    ///--------------------- E. Data object characteristics and object identifiers ---------------------///
    ///------------------ MANDATORY
    this.resourceTypeGeneral,

    ///------------------ RECOMMENDED
    this.resourceType,
    this.description,
    this.language,
    this.relatedIdentifiers,

    ///------------------ OPTIONAL
    this.subjectsOfDataObject,

    ///--------------------- F. Identifying location, ownership and access ---------------------///
    ///------------------ MANDATORY
    this.publisher,
    this.accessType,
    this.accessDetails,
    this.accessContact,
    this.resources,

    ///------------------ RECOMMENDED
    this.otherHostingInstitutions,

    ///------------------ OPTIONAL
    this.rights,
  });

  int? ID;
  String? data_source;
  String? file_name;

  ///--------------------- A. The source study or studies ---------------------///

  ///------------------ MANDATORY
  List<String>? sourceStudyTitle;

  /*
    The source study title is the name of the study or studies that the data object describes, was generated by, and/or refers to (but not those it simply cites).
    The ‘name’ in this instance means the full or ‘scientific’ title (i.e., the title of the study protocol).
    For the sake of consistency, it should be the exact title as used on version 1.0 of the protocol.'
    */

  ///------------------ RECOMMENDED
  List<String>? studyIdentifierRecords;

  /*
    The study identifier comprises none, one or more unique identifiers that have been assigned.
    There is no assumption that a study will have an identifier of a particular type.
    For studies entered into trial registries, these should include, at minimum, the registry ID(s), but any IDs that have been externally applied and that might be useful in identifying the study can be included.
    These IDs are composite.
    If provided, they must include not just the identifier value and type but also the assigning organisation, the scheme uniform resource identifier (URI) if there is one, and optionally the date the identifier was assigned (see Additional file 1).
    (Options used for identifier type and assigning organisation could be common with the lists used for DOIs, as described in B.2 below).
    */

  List<String>? studyTopics;

  /*
    The study topics comprise none, one or more topic names or phrases, keywords, or classification codes describing the study or aspects of it.
    Topics is preferred to subjects because ‘Study subjects’ is normally understood as referring to the study participants.
    In the context of clinical research data objects, it makes sense to include any topic data with the study rather than the individual data objects relating to that study.
    */

  ///------------------ OPTIONAL

  ///--------------------- B. Data object characteristics and object identifiers  ---------------------///

  ///------------------ MANDATORY
  String?
      DOI; // Digital object identifier // (1) Mandatory for publicly accessible data objects, recommended for all others
  /*
    Data objects available publicly, such as journal articles, plus some of the data sets and protocols in repositories, should have a DOI (in line with the DataCite specification).
    As discussed in the Methods section above, non-public data objects should also, wherever possible, also have a DOI.
    If a DOI is not possible, or has not yet been assigned, then the object should be identified either by an accession number from a metadata repository system or by using the object’s name and version code, coupled with a unique identifier for the source study.
    The data object identifier (like study identifiers) therefore needs to be a composite, indicating its type and source as well as its value.
    */

  String? objectTitle;

  /*
    Within the context of the associated study or studies, the default name of the data object should be unique.
    Additional names can also be provided.
    If given, they are composite: the title plus one of ‘title type’ (e.g., translated title, alternative title, subtitle).
    */

  ///------------------ RECOMMENDED
  String? version;

  /*
    Optionally, the version code for the data object is used.
    Many versions of a particular data set or document may have been created in the course of a clinical study, but the focus here is on the version or versions that are made available for sharing.
    The data generators will need to make that selection, though the normal expectation would be that the final version of a data object (e.g., a protocol) would be the one that was shared with others.
    */

  ///------------------ OPTIONAL
  List<String>? objectOtherIdentifiers;

  /*
    ‘Other object identifiers’ refers to other unique identifiers that have been assigned to the data object in addition to its primary identifier.
    Again, such IDs would be composite and include the identifier type and assigning organisation, as well as its value, and optionally the identifier scheme and date of assignment.
    The lists used for identifier type and assigning organisation could be common with the lists used for study identifiers.
    */

  List<String>? objectAdditionalTitles;

  /*
    Within the context of the associated study or studies, the default name of the data object should be unique.
    Additional names can also be provided.
    If given, they are composite: the title plus one of ‘title type’ (e.g., translated title, alternative title, subtitle).
    */

  ///--------------------- C. Data object characteristics and object identifiers ---------------------///

  ///------------------ MANDATORY
  List<String>? creators;

  /*
    The creators are the main personnel involved in producing the data, or the authors of a publication. It may be a set of institutional or personal names.
    Each name in the list is a composite element and can contain optional identifiers (e.g., Open Researcher Contributor Identification [‘ORCID’] identifiers and/or organisational affiliations, as well as the name itself).
    */

  ///------------------ RECOMMENDED

  ///------------------ OPTIONAL
  String? contributors;

  /*
    Optionally, other institutions and/or persons responsible for collecting, managing, distributing or otherwise contributing to the development of the data object can be included.
    f given, any contributor record is composite, with the same structure as the Creator data above, plus an additional data point specifying contributor type.
    The latter may need extending in the context of clinical research to include, for example, drug supplier, drug distributor, device manufacturer, central laboratory, sponsor contact, recruitment contact, principal and chief (or co-ordinating) investigator.
    */

  ///--------------------- D. Data object characteristics and object identifiers ---------------------///

  ///------------------ MANDATORY
  String? creationYear;

  /*
    The creation year is the year in which the object was created, expressed as four digits.
    Its precise definition will vary with the nature of the data object.
    For data sets, it will be the year of their extraction; for published documents, the year of their initial publication; and for internal documents, the year of their approval for use.
    Note that ‘creation year’ is intended only to provide an indicator of the time something was created (e.g., in an on-screen listing).
    It is not a date, which is collected and stored separately (see D.2 below).
    */

  ///------------------ RECOMMENDED

  ///------------------ OPTIONAL
  List<String>? dates;

  /*
    None, one or more dates or date ranges that are relevant to the data object, in the standard ISO 8601 format, are used.
    Each date should be accompanied by a date type value that indicates what the date represents, such as accepted, available, copyrighted, collected, created, issued, submitted, updated, valid.
    This list (from DataCite) may need extending to better span the clinical research domain.
    */

  ///--------------------- E. Data object characteristics and object identifiers ---------------------///

  ///------------------ MANDATORY
  String? resourceTypeGeneral;

  /*
    Resource type is one of the existing DataCite controlled list.
    In most cases, for clinical research data objects, the type will be ‘text’ or ‘data set’.
    */

  ///------------------ RECOMMENDED
  String? resourceType;

  /*
    Resource type is a description of the resource.
    The format is open, but the preferred format is a single term, so that a pair can be formed with the ‘resource type general’ described above (e.g., data set/census data or text/conference abstract).
    Existing types will need extending by a list of standard resource types for clinical research (e.g., protocol, patient information sheet, final analysis data set, quality of life data set).
    In practice, an expandable list would be needed (i.e., one where a user could supplement the supplied controlled vocabulary terms by free text, as and when necessary).
    */

  List<String>? description;

  /*
    The description comprises none, one or more pieces of additional general information.
    The format is open, but any description should be accompanied by a description type to further characterise the data: one of abstract, methods, series information, table of contents, other.
    */

  String? language;

  /*
    The language is the primary language of the resource, using the International Organisation for Standardisation (ISO) language codes (e.g., EN, DE, FR).
    */

  List<String>? relatedIdentifiers;

  /*
    Related identifiers are the identifiers of related resources, which must be globally unique identifiers. Related resources will normally be data objects themselves.
    The record is composite and must include the identifier itself, the related identifier type and the relation type. Relation types include IsCitedBy, Cites, IsSupplementTo, IsSupplementedBy, IsContinuedBy, Continues, IIDewVersionOf, IsPreviousVersionOf, IsPartOf, HasPart, IsIdenticalTo, IsDerivedFrom and IsSourceOf.
    */

  ///------------------ OPTIONAL
  List<String>? subjectsOfDataObject;

  /*
    Subjects comprise none, one or more subject names or phrases, keywords, classification codes describing the resource.
    In general, however, the recommendation is to include any subject or topic descriptors, keywords, and so forth, with the study data rather than the individual data objects (see A.3 above).
    */

  ///--------------------- F. Identifying location, ownership and access ---------------------///

  ///------------------ MANDATORY
  String? publisher;

  /*
    In this schema, this is the organisation that manages access to the document, including making the overall decision about access type (see F.3).
    For data, this would be the name of the organisation managing the repository.
    For journal papers, it is the name of the company that publishes the journal and which would normally run the primary website on which it can be accessed.
    */

  String? accessType;

  /*
    Access type is one of ‘public download’, ‘public on-screen access’, ‘restricted download’, ‘restricted on-screen access’, ‘case-by-case download’ or ‘case-by-case on-screen access’.
    Restricted means access would be dependent on membership of a predefined group, usually as determined by an authentication mechanism (e.g., username with password), such as is the case with subscription to a journal.
    Case-by-case means that there is no predefined access, but that applications for access to the data object will be considered by the object owners.
    On-screen access means that a researcher can view and process data within a specified environment but cannot download a file of the raw data, though export of the results of re-analysis would be allowed.
    */

  String? accessDetails; // (2) Mandatory if access is non-public
  /*
    Access details refers to a textual description of the access being offered, such as identifying the groups to which access is granted, the criteria on the basis of which a case-by-case decision would be based, or any further restrictions on on-screen access.
     */

  String? accessContact; // (2) Mandatory if access is non-public
  /*
    Access contact is a link to a resource that explains how access may be gained, such as how a group can be joined, and/or how application can be made for access on an individual basis.
    This could include an email address but more normally would be a link to a web page on the publisher’s site that would explain access procedures or provide an application pro forma.
     */

  List<String>? resources;

  /*
    Resources comprise the web-based resources that represent this data object.
    This is mandatory for public or restricted access objects when at least one resource should be listed.
    Each record would be composite and include the F.6.1 resource URL and, if downloadable, the F.6.2 resource file type (e.g., file extension or Multipurpose Internet Mail Extension [‘MIME’] type) and the F.6.3 resource size, usually in kilobytes or megabytes.
    The resource host would usually be obvious from the URL.
     */

  ///------------------ RECOMMENDED
  List<String>? otherHostingInstitutions;

  /*
    Other hosting institutions are any organisations other than the publisher identified in F.1 that also host the data object within their IT infrastructure.
    */

  ///------------------ OPTIONAL
  List<String>? rights;

/*
    Rights include any intellectual property rights information for the data object, as a textual statement of the rights management associated with the resource.
    The URI for the specific rights management should also be given (F.7.1).
 */

  factory ResearchDocumentModel.fromJson(Map<String, dynamic> json) =>
      ResearchDocumentModel(
        ID: json["ID"] ?? null,
        data_source: json["data_source"] ?? null,
        file_name: json["file_name"] ?? null,

        ///--------------------- A. The source study or studies ---------------------///
        ///------------------ MANDATORY
        sourceStudyTitle: json["data_source"] ?? null,

        ///------------------ RECOMMENDED
        studyIdentifierRecords: json["studyIdentifierRecords"] ?? null,
        studyTopics: json["studyTopics"] ?? null,

        ///------------------ OPTIONAL

        ///--------------------- B. Data object characteristics and object identifiers  ---------------------///
        ///------------------ MANDATORY
        DOI: json["DOI"] ?? null,
        objectTitle: json["objectTitle"] ?? null,

        ///------------------ RECOMMENDED
        version: json["version"] ?? null,

        ///------------------ OPTIONAL
        objectOtherIdentifiers: json["objectOtherIdentifiers"] ?? null,
        objectAdditionalTitles: json["objectAdditionalTitles"] ?? null,

        ///--------------------- C. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        creators: json["creators"] ?? null,

        ///------------------ RECOMMENDED
        ///------------------ OPTIONAL
        contributors: json["contributors"] ?? null,

        ///--------------------- D. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        creationYear: json["creationYear"] ?? null,

        ///------------------ RECOMMENDED
        ///------------------ OPTIONAL
        dates: json["dates"] ?? null,

        ///--------------------- E. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        resourceTypeGeneral: json["resourceTypeGeneral"] ?? null,

        ///------------------ RECOMMENDED
        resourceType: json["resourceType"] ?? null,
        description: json["description"] ?? null,
        language: json["language"] ?? null,
        relatedIdentifiers: json["relatedIdentifiers"] ?? null,

        ///------------------ OPTIONAL
        subjectsOfDataObject: json["subjectsOfDataObject"] ?? null,

        ///--------------------- F. Identifying location, ownership and access ---------------------///
        ///------------------ MANDATORY
        publisher: json["publisher"] ?? null,
        accessType: json["accessType"] ?? null,
        accessDetails: json["accessDetails"] ?? null,
        accessContact: json["accessContact"] ?? null,
        resources: json["resources"] ?? null,

        ///------------------ RECOMMENDED
        otherHostingInstitutions: json["otherHostingInstitutions"] ?? null,

        ///------------------ OPTIONAL
        rights: json["rights"] ?? null,
      );

  Map<String, dynamic> toJson() => {
        "ID": ID ?? null,
        "data_source": data_source ?? null,
        "file_name": file_name ?? null,

        ///--------------------- A. The source study or studies ---------------------///
        ///------------------ MANDATORY
        "sourceStudyTitle": sourceStudyTitle ?? null,

        ///------------------ RECOMMENDED
        "studyIdentifierRecords": studyIdentifierRecords ?? null,
        "studyTopics": studyTopics ?? null,

        ///------------------ OPTIONAL

        ///--------------------- B. Data object characteristics and object identifiers  ---------------------///
        ///------------------ MANDATORY
        "DOI": DOI ?? null,
        "objectTitle": objectTitle ?? null,

        ///------------------ RECOMMENDED
        "version": version ?? null,

        ///------------------ OPTIONAL
        "objectOtherIdentifiers": objectOtherIdentifiers ?? null,
        "objectAdditionalTitles": objectAdditionalTitles ?? null,

        ///--------------------- C. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        "creators": creators ?? null,

        ///------------------ RECOMMENDED
        ///------------------ OPTIONAL
        "contributors": contributors ?? null,

        ///--------------------- D. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        "creationYear": creationYear ?? null,

        ///------------------ RECOMMENDED
        ///------------------ OPTIONAL
        "dates": dates ?? null,

        ///--------------------- E. Data object characteristics and object identifiers ---------------------///
        ///------------------ MANDATORY
        "resourceTypeGeneral": resourceTypeGeneral ?? null,

        ///------------------ RECOMMENDED
        "resourceType": resourceType ?? null,
        "description": description ?? null,
        "language": language ?? null,
        "relatedIdentifiers": relatedIdentifiers ?? null,

        ///------------------ OPTIONAL
        "subjectsOfDataObject": subjectsOfDataObject ?? null,

        ///--------------------- F. Identifying location, ownership and access ---------------------///
        ///------------------ MANDATORY
        "publisher": publisher ?? null,
        "accessType": accessType ?? null,
        "accessDetails": accessDetails ?? null,
        "accessContact": accessContact ?? null,
        "resources": resources ?? null,

        ///------------------ RECOMMENDED
        "otherHostingInstitutions": otherHostingInstitutions ?? null,

        ///------------------ OPTIONAL
        "rights": rights ?? null,
      };
}
